### ISSUE TITLE
Naming conventions 

### ISSUE THREAD

**Issue by BenjaminPeter** [stephens999/dscr#44]
It would be nice to keep function names consistent.

Currently, there are functions that are dot separated (`new.dsc`), camelCase (`addMethod`) and underscore delimited (`run_dsc`). It would be nice to make the names consistent in one way or the other.

**Comment by stephens999** [comment]
I agree. After discussions with @ramanshah I think we should employ snake_case throughout. Perhaps we can keep the old functions around initially in a deprecated.R file, with a call to the new functions so that existing dscs will continue to run. But I think better to make this change sooner rather than later.

**Comment by ramanshah** [comment]
Resolved by #52.

**Comment by ramanshah** [comment]
@stephens999 Sorry, I forgot to put the magic issue-closing stuff in the relevant git commit - please close. :)
