### ISSUE TITLE
create gold standard methods

### ISSUE THREAD

**Issue by stephens999** [stephens999/dscr#60]
sometimes it is helpful to compare a method with a "gold standard" method that could not
actually be run in practice. To do this is would be good to add a new type of method, that instead of taking input, takes data=(meta,input). The idea is that the gold method has access not only to the input, but also to meta. This allows the method to "cheat". The only difference in implementation between a gold_method and a method would be that it is passed data instead of input.

I guess I envisage adding a flag for each method saying whether or not it is a "gold" method.
Then we can add a function
add_gold_method
or overload add_method with a new parameter gold=TRUE/FALSE.
so that the user can add a gold method.
Finally when we run a method, we would have to check whether it is flagged as gold. If so then
it gets passed data=(meta,input); otherwise it gets passed just input.

thoughts @ramanshah ?

**Comment by ramanshah** [comment]
Why not just have the "gold" method be a stub that emits a flag that alerts the user's scoring function to emit a "gold" score? The scoring function already has access to input/output/meta, so the logic can live there.

e.g.:

```
gold_wrapper <- function(input, args) {
  return('gold_flag')
}

add_method(dsc, name = 'gold', fn = gold_wrapper, args = NULL)

score <- function(data, output) {
  if (output == 'gold_flag') {
    # here, you have access to input, meta, and output, so you can do whatever you want
  }
  ## ...
}

add_score(dsc, score)
```

If we are not "strict" about the semantics on whether input/output/meta objects actually contain input/output/metadata, I think this is the way to go in the name of usability - if there is a choice between letting users create complexity on their own or giving them complexity to learn, I always vote for the former, because then the users will at least intimately know the quirks.

**Comment by ramanshah** [comment]
Even better, perhaps, is to encode the "goldness" in the `output_type`, and you can have a gold scorer that is separated from the good-faith scorers.

**Comment by stephens999** [comment]
hmm, i don't like the gold scoring function because the logic is that the score is the same for all methods... and it doesn't seem like it would be easy to have two different "gold standard" methods? (ok, so maybe "silver standard" would be better).  Also I prefer to keep non-trivial computation in the methods...

**Comment by stephens999** [comment]
hmm, i think my use case may not be clear to you from the trivial vignette...
i think for what i have in mind my implementation is preferable

**Comment by ramanshah** [comment]
OK then.
